#!/usr/bin/env python3

# stq: A Mercurial-Queues-like wrapper for StGit

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

VERSION = "0.3.0"

# Color definitions
COLOR_BLACK = "\x1b[30m"
COLOR_RED = "\x1b[31m"
COLOR_GREEN = "\x1b[32m"
COLOR_YELLOW = "\x1b[33m"
COLOR_BLUE = "\x1b[34m"
COLOR_MAGENTA = "\x1b[35m"
COLOR_CYAN = "\x1b[36m"
COLOR_WHITE = "\x1b[37m"
COLOR_GRAY = "\x1b[90m"  # Bright Black
COLOR_BOLD = "\x1b[1m"
COLOR_UNDERLINE = "\x1b[4m"
COLOR_RESET = "\x1b[m"

# Color configurations
COL_APPLIED = COLOR_BOLD + COLOR_UNDERLINE + COLOR_BLUE
COL_UNAPPLIED = COLOR_BOLD + COLOR_GRAY
COL_UNGUARDED = COLOR_GREEN
COL_POS_GUARD = COLOR_YELLOW
COL_NEG_GUARD = COLOR_RED
COL_OFF = COLOR_RESET


class Configurations:
    def __init__(self):
        # TODO: Load settings from a setting file
        self.stg = "stg"
        self.git = "git"


conf = Configurations()


def does_search_across_fs() -> bool:
    val = os.getenv("GIT_DISCOVERY_ACROSS_FILESYSTEM", "")
    return val == "1" or val.lower() == "true"


def get_git_topdir(path: Optional[Path] = None) -> Optional[Path]:
    """Get the git toplevel directory.
    Same as `git rev-parse --show-toplevel`.
    """
    if not path:
        path = Path.cwd()
    path = path.resolve()
    while True:
        if (path / ".git").exists():
            return path
        parent = path.parent
        if parent.is_mount() and not does_search_across_fs():
            # Filesystem boundary
            return None
        if parent == path:
            # Root directory.
            return None
        # TODO: Check GIT_CEILING_DIRECTORIES
        path = parent


def get_gitdir(path: Optional[Path] = None) -> Optional[Path]:
    """Get the git directory. (E.g. ".git")
    Same as `git rev-parse --git-dir` except that this returns an absolute path.
    """
    gittop = get_git_topdir(path)
    if not gittop:
        return None
    gitdir = gittop / ".git"
    if gitdir.is_dir():
        return gitdir
    if gitdir.is_file():
        with gitdir.open() as f:
            s = f.readline()
            m = re.match(r"gitdir: (.+)$", s)
            if m:
                gitdir = gittop / m.group(1)
                if gitdir.is_dir():
                    return gitdir
    return None


def get_patchesdir(path: Optional[Path] = None) -> Optional[Path]:
    """Get the patches directory. (E.g. ".git/stq-patches")"""
    git_dir = get_gitdir(path)
    if not git_dir:
        return None
    return git_dir / "stq-patches"


def ensure_patchesdir(path: Optional[Path] = None, create: bool = False) -> Path:
    patdir = get_patchesdir(path)
    if not patdir:
        print("stq: .git directory not found.", file=sys.stderr)
        sys.exit(1)
    if not patdir.exists():
        if create:
            patdir.mkdir(exist_ok=True)
        else:
            print("stq: Please run 'stq init' first.", file=sys.stderr)
            sys.exit(1)
    return patdir


def read_guards(guards: Path) -> list[str]:
    guards_list: list[str] = []

    if not guards.exists():
        return guards_list

    with guards.open() as f:
        for s in f.readlines():
            guards_list += [s.strip()]

    return guards_list


def write_guards(guards: Path, guards_list: list[str]) -> None:
    with guards.open("w") as f:
        for s in guards_list:
            print(s, file=f)


class SeriesItem:
    def __init__(
        self,
        patchfile: str,
        patchname: str,
        positive_guards: list[str],
        negative_guards: list[str],
        applied: Optional[str] = None,  # None, "applied", "unapplied"
        guarded: Optional[str] = None,  # None, "guarded", "unguarded"
        commitid: Optional[str] = None,
        registered: Optional[bool] = None,
    ):
        assert applied in [None, "applied", "unapplied"]
        assert guarded in [None, "guarded", "unguarded"]

        self.patchfile = patchfile
        self.patchname = patchname
        self.positive_guards = positive_guards
        self.negative_guards = negative_guards
        self.applied = applied
        self.guarded = guarded
        self.commitid = commitid
        self.registered = registered


class StgSeriesItem:
    def __init__(
        self,
        patchname: str,
        applied: bool,
    ):
        self.patchname = patchname
        self.applied = applied


class StatusItem:
    def __init__(self, commitid: str, patchname: str):
        self.commitid = commitid
        self.patchname = patchname


def read_series(series: Path) -> list[SeriesItem]:
    series_list: list[SeriesItem] = []

    if not series.exists():
        return series_list

    with series.open() as f:
        for s in f.readlines():
            patchfile, *items = s.split()

            if patchfile.startswith("#"):
                # Skip comment
                continue

            patchname = patchfile
            positive_guards: list[str] = []
            negative_guards: list[str] = []

            for i in items:
                t = i[:2]
                name = i[2:]

                if t == "#=":
                    patchname = name
                elif t == "#+":
                    positive_guards += [name]
                elif t == "#-":
                    negative_guards += [name]
                else:
                    # Ignore other (special) comments
                    pass

            series_list += [
                SeriesItem(patchfile, patchname, positive_guards, negative_guards)
            ]

    return series_list


def write_series(series: Path, series_list: list[SeriesItem]) -> None:
    with series.open("w") as f:
        for si in series_list:
            s = si.patchfile
            if si.patchname and si.patchname != si.patchfile:
                s += f" #={si.patchname}"
            if si.positive_guards:
                for i in si.positive_guards:
                    s += f" #+{i}"
            if si.negative_guards:
                for i in si.negative_guards:
                    s += f" #-{i}"
            print(s, file=f)


def update_or_add_to_series(
    series_list: list[SeriesItem], patchname: str, insert_idx: int, applied: bool
) -> tuple[str, bool]:
    # Search patchname from series_list
    for si in series_list:
        if si.patchname == patchname or si.patchfile == patchname:
            # Found. Update it.
            if applied:
                si.commitid = ""  # get_stg_commitid(patchname)
                si.applied = "applied"
            else:
                si.applied = "unapplied"
            return si.patchfile, False

    # Not found, add to series_list
    if insert_idx == -1:
        insert_idx = len(series_list)
    if applied:
        applied_str = "applied"
        commitid = ""  # get_stg_commitid(patchname)
    else:
        applied_str = "unapplied"
        commitid = None
    series_list.insert(
        insert_idx,
        SeriesItem(patchname, "", [], [], applied_str, "unguarded", commitid),
    )
    return patchname, True


def update_series_by_guards(
    series_list: list[SeriesItem], guards_list: list[str]
) -> None:
    for si in series_list:
        if si.positive_guards:
            guarded = "guarded"
        else:
            guarded = "unguarded"

        for pg in si.positive_guards:
            if pg in guards_list:
                guarded = "unguarded"
        for ng in si.negative_guards:
            if ng in guards_list:
                guarded = "guarded"

        si.guarded = guarded


def update_series_by_status(
    series_list: list[SeriesItem], status_list: list[StatusItem]
) -> None:
    for si in series_list:
        if si.patchname:
            patchname = si.patchname
        else:
            patchname = si.patchfile

        applied = "unapplied"
        for sti in status_list:
            if patchname == sti.patchname:
                applied = "applied"

        si.applied = applied


def update_series_by_stg_series(
    series_list: list[SeriesItem],
    patch_list: list[StgSeriesItem],
):
    # Add the patches that are registered in stg series to stq series.
    # If already added, update it.
    idx = get_last_applied_patch_idx(series_list) + 1
    for p in patch_list:
        _, added = update_or_add_to_series(series_list, p.patchname, idx, p.applied)
        if added:
            idx += 1

    # Update applied status
    for si in series_list:
        if p := get_matching_patch_in_stg_series(patch_list, si.patchname):
            si.registered = True
            if p.applied:
                si.applied = "applied"
            else:
                si.applied = "unapplied"
        else:
            si.registered = False
            si.applied = "unapplied"


def get_matching_patch_idx(series_list: list[SeriesItem], patch: str) -> int:
    for i, si in enumerate(series_list):
        if si.patchfile == patch or si.patchname == patch:
            return i
    return -1


def get_matching_patch(
    series_list: list[SeriesItem], patch: str
) -> Optional[SeriesItem]:
    if (i := get_matching_patch_idx(series_list, patch)) >= 0:
        return series_list[i]
    return None


def get_last_applied_patch_idx(series_list: list[SeriesItem]) -> int:
    idx = -1
    for i, si in enumerate(series_list):
        if si.applied == "applied":
            idx = i
    return idx


def get_last_applied_patch(series_list: list[SeriesItem]) -> Optional[SeriesItem]:
    if (i := get_last_applied_patch_idx(series_list)) >= 0:
        return series_list[i]
    return None


def get_ungarded_patch_list(
    series_list: list[SeriesItem], start_idx: int = -1
) -> list[SeriesItem]:
    filtered_list: list[SeriesItem] = []
    if start_idx < 0:
        idx = get_last_applied_patch_idx(series_list)
    else:
        idx = start_idx
    for si in series_list[idx + 1 :]:
        if si.guarded == "unguarded":
            filtered_list += [si]
    return filtered_list


def get_stg_commitid(patchname: str) -> str:
    proc = subprocess.Popen(
        # Show only commit ID
        [
            conf.stg,
            "show",
            "--diff-opts=--no-patch",
            "--diff-opts=--format=%H",
            patchname,
        ],
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    assert proc.stdout

    return proc.stdout.readline().rstrip()


def run_stg_series(status: str = "all") -> list[StgSeriesItem]:
    assert status in ["all", "applied", "unapplied"]

    stgcmd = [conf.stg, "series"]
    if status == "applied":
        stgcmd += ["--applied"]
    elif status == "unapplied":
        stgcmd += ["--unapplied"]

    proc = subprocess.Popen(
        stgcmd,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    assert proc.stdout

    patch_list: list[StgSeriesItem] = []
    while True:
        line = proc.stdout.readline()
        if not line:
            if proc.poll() is not None:
                break
            continue
        status, patch = line.rstrip().split(maxsplit=1)
        if status == "+" or status == ">":
            applied = True
        else:
            applied = False
        patch_list += [StgSeriesItem(patch, applied)]

    return patch_list


def read_status(status: Path) -> list[StatusItem]:
    status_list: list[StatusItem] = []

    if not status.exists():
        return status_list

    with status.open() as f:
        for s in f.readlines():
            if s:
                commitid, patchname = s.rstrip().split(":")
                status_list += [StatusItem(commitid, patchname)]

    return status_list


def write_status(status: Path, status_list: list[StatusItem]) -> None:
    with status.open("w") as f:
        for sti in status_list:
            print(f"{sti.commitid}:{sti.patchname}", file=f)


def write_status_from_series(status: Path, series_list: list[SeriesItem]) -> None:
    with status.open("w") as f:
        for si in series_list:
            if si.applied == "applied":
                patchname = si.patchname if si.patchname else si.patchfile
                print(f"{si.commitid}:{patchname}", file=f)


def command_clean(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    if not args.unapplied:
        # If the current stg patch is empty, and if there are changes
        # in the work directory, we don't want to delete it.

        # TODO: Check if the current stg patch is empty.

        # Run "git diff"
        res = subprocess.run([conf.git, "diff", "HEAD", "--quiet"])
        if res.returncode:
            print("stq: Local changes found.", file=sys.stderr)
            sys.exit(res.returncode)

    patch_list = run_stg_series()
    if len(patch_list) == 0:
        print("stq: No patches registered in StGit.")
        return
    update_series_by_stg_series(series_list, patch_list)

    # Run "stg clean"
    stgcmd = [conf.stg, "clean"]
    if args.applied:
        stgcmd += ["--applied"]
    if args.unapplied:
        stgcmd += ["--unapplied"]
    res = subprocess.run(stgcmd)
    if res.returncode:
        sys.exit(res.returncode)

    # Update series based on the new stg series
    new_patch_list = run_stg_series()
    new_series_list: list[SeriesItem] = []
    remove_list: list[SeriesItem] = []
    for si in series_list:
        if not si.registered or get_matching_patch_in_stg_series(
            new_patch_list, si.patchname
        ):
            new_series_list += [si]
        else:
            remove_list += [si]

    if not args.keep:
        for si in remove_list:
            patch_path = patdir / si.patchfile
            if patch_path.exists():
                patch_path.unlink()

    write_series(series, new_series_list)
    write_status_from_series(status, new_series_list)


def command_clone(args: argparse.Namespace):
    # Run "stg clone"
    res = subprocess.run([conf.stg, "clone", args.repository, args.dir])
    if res.returncode:
        sys.exit(res.returncode)

    if args.patches:
        # Run "git clone" for patdir
        res = subprocess.run(
            [conf.git, "clone", args.patches, f"{args.dir}/.git/stq-patches"]
        )
        if res.returncode:
            sys.exit(res.returncode)
    else:
        init_stq(skip_stg=True)


def command_delete(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    remove_list: list[SeriesItem] = []
    if args.top:
        si = get_last_applied_patch(series_list)
        if not si:
            print("stq: No patches applied", file=sys.stderr)
            sys.exit(1)
        remove_list += [si]
    else:
        if not args.patch:
            print("stq: No patches specified", file=sys.stderr)
            sys.exit(1)
        for patch in args.patch:
            for si in series_list:
                if si.patchfile == patch or si.patchname == patch:
                    # Patch found
                    if si.applied == "applied":
                        print(
                            f'stq: Cannot delete applied patch: "{patch}"',
                            file=sys.stderr,
                        )
                        sys.exit(1)
                    remove_list += [si]
                    break
            else:
                print(f'stq: Patch not found: "{patch}"', file=sys.stderr)
                sys.exit(1)

    # Run "stg delete"
    if args.top:
        returncode = subprocess.run([conf.stg, "delete", "--top"]).returncode
    else:
        patch_list = run_stg_series()
        patch_names = [
            si.patchname
            for si in remove_list
            if get_matching_patch_in_stg_series(patch_list, si.patchname)
        ]
        if patch_names:
            returncode = subprocess.run(
                [conf.stg, "delete", "--"] + patch_names
            ).returncode
        else:
            returncode = 0
    if returncode:
        sys.exit(returncode)

    for si in remove_list:
        if not args.keep:
            patch_path = patdir / si.patchfile
            if patch_path.exists():
                patch_path.unlink()
        series_list.remove(si)
    write_series(series, series_list)


def command_discard(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    if args.all:
        print("Popping all patches...")
        pop_patches(popall=True, ignore_nopatches=True)

        patch_list = run_stg_series()
        if len(patch_list) == 0:
            print("stq: No patches registered in StGit.")
            return

        # Run "stg delete"
        print("Deleting all patches from StGit...")
        patch_names = [p.patchname for p in patch_list]
        res = subprocess.run([conf.stg, "delete", "--"] + patch_names)
        if res.returncode:
            sys.exit(res.returncode)

    elif args.top:
        series = patdir / "series"
        series_list = read_series(series)
        status = patdir / "status"
        status_list = read_status(status)
        guards = patdir / "guards"
        guards_list = read_guards(guards)

        update_series_by_guards(series_list, guards_list)
        update_series_by_status(series_list, status_list)

        si = get_last_applied_patch(series_list)
        if not si:
            print("stq: No patches applied", file=sys.stderr)
            sys.exit(1)

        print("Popping the top patch...")
        pop_patches(patchname=si.patchfile, ignore_nopatches=True)
        print("Deleting the top patch from StGit...")
        res = subprocess.run([conf.stg, "delete", "--", si.patchname])
        if res.returncode:
            sys.exit(res.returncode)


def command_edit(args: argparse.Namespace, argv: list[str]):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    si = get_last_applied_patch(series_list)
    if not si:
        print("stq: No patches applied", file=sys.stderr)
        sys.exit(1)

    # Run "stg edit"
    stgcmd = [conf.stg, "edit"] + argv
    res = subprocess.run(stgcmd)
    if res.returncode:
        sys.exit(res.returncode)

    # Update the current patch file
    refresh_patch(patdir, si)


def get_matching_patch_in_stg_series(
    patch_list: list[StgSeriesItem], patch: str
) -> Optional[StgSeriesItem]:
    for p in patch_list:
        if p.patchname == patch:
            return p
    return None


def command_fold(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    last_si = get_last_applied_patch(series_list)
    if not last_si:
        print("stq: No patches applied", file=sys.stderr)
        sys.exit(1)

    patch_list = run_stg_series("unapplied")

    for patchname in args.patch:
        si = get_matching_patch(series_list, patchname)
        if not si:
            print(f"stq: Patch not found: {patchname}", file=sys.stderr)
            sys.exit(1)
        patchpath = patdir / si.patchfile

        if get_matching_patch_in_stg_series(patch_list, si.patchname):
            # Run "stg squash"
            res = subprocess.run([conf.stg, "squash", "--", si.patchname])
        else:
            # Run "git apply --index"
            res = subprocess.run([conf.git, "apply", "--index", str(patchpath)])
            if res.returncode:
                sys.exit(res.returncode)
            # Run "stg refresh"
            res = subprocess.run([conf.stg, "refresh"])

        if res.returncode:
            sys.exit(res.returncode)

        series_list.remove(si)
        if not args.keep:
            patchpath.unlink()

    write_series(series, series_list)

    # Update the current patch file
    refresh_patch(patdir, last_si)


def show_guard_status(si: SeriesItem):
    if si.applied == "applied":
        print(f"{COL_APPLIED}{si.patchfile}{COL_OFF}:", end="")
    elif si.applied == "unapplied":
        print(f"{COL_UNAPPLIED}{si.patchfile}{COL_OFF}:", end="")
    else:
        print(f"{si.patchfile}:", end="")

    if si.positive_guards or si.negative_guards:
        for i in si.positive_guards:
            print(f" {COL_POS_GUARD}+{i}{COL_OFF}", end="")
        for i in si.negative_guards:
            print(f" {COL_NEG_GUARD}-{i}{COL_OFF}", end="")
    else:
        print(f" {COL_UNGUARDED}unguarded{COL_OFF}", end="")
    print()


def show_guard_list(series_list: list[SeriesItem]):
    for si in series_list:
        show_guard_status(si)


def command_guard(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    patch = args.patch
    guard = args.guard

    if args.list:
        # Show guards list
        show_guard_list(series_list)
        return

    if patch is not None:
        if len(patch) > 0 and (patch[0] == "+" or patch[0] == "-"):
            guard.insert(0, patch)
            patch = None

    if patch:
        si = get_matching_patch(series_list, patch)
        if not si:
            print(f"stq: No patch named {patch}", file=sys.stderr)
            sys.exit(1)
    else:
        si = get_last_applied_patch(series_list)
        if not si:
            print("stq: No patches applied", file=sys.stderr)
            sys.exit(1)

    if not guard and not args.none:
        # Show guards of the patch
        show_guard_status(si)
        return

    # Update series
    positive_guards: list[str] = []
    negative_guards: list[str] = []
    for g in guard:
        if len(g) <= 1 or (g[0] != "+" and g[0] != "-"):
            print(
                f'stq: Wrong guard name: {g}, must be prefixed by "+" or "-"',
                file=sys.stderr,
            )
        if g[0] == "+":
            positive_guards += [g[1:]]
        if g[0] == "-":
            negative_guards += [g[1:]]

    si.positive_guards = positive_guards
    si.negative_guards = negative_guards
    write_series(series, series_list)


def import_patches(patches: list[Path]) -> None:
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    added_patches: list[SeriesItem] = []
    for patch in patches:
        print(f"stq: Importing {patch}")
        if get_matching_patch(series_list, patch.name):
            print(f"stq: Same patch name already exists: {patch.name}", file=sys.stderr)
            sys.exit(1)
        shutil.copy(patch, patdir)
        added_patches += [SeriesItem(patch.name, "", [], [])]

    series_list += added_patches
    write_series(series, series_list)


def command_import(args: argparse.Namespace):
    import_patches(args.patch)


def command_mqimport(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    if not args.mq_dir.is_dir():
        print(f"stq: Error: not a directory: {args.mq_dir}", file=sys.stderr)
        sys.exit(1)

    series = args.mq_dir / "series"
    if not series.is_file():
        print(f"stq: Error: series file not found in {args.mq_dir}", file=sys.stderr)
        sys.exit(1)

    if (patdir / "series").is_file():
        print(f"stq: Error: series file already exists in {patdir}", file=sys.stderr)
        sys.exit(1)

    series_list = read_series(series)
    for si in series_list:
        patch = args.mq_dir / si.patchfile
        print("Copying:", patch)
        shutil.copy(patch, patdir)

    print("Copying:", series)
    shutil.copy(series, patdir)

    guards = args.mq_dir / "guards"
    if guards.is_file():
        print("Copying:", guards)
        shutil.copy(guards, patdir)


def init_stq(skip_stg: Optional[bool]):
    # Create .git/patches directory
    patdir = ensure_patchesdir(create=True)

    # Create .gitignore
    gitign = patdir / ".gitignore"
    if not gitign.exists():
        with gitign.open("w") as f:
            print("guards", file=f)
            print("status", file=f)

    if not skip_stg:
        # Run "stg init"
        res = subprocess.run([conf.stg, "init"])
        if res.returncode:
            sys.exit(res.returncode)


def command_init(args: argparse.Namespace):
    init_stq(args.skip_stg)


def run_stg_new(
    patchname: str, message: str = "", argv: Optional[list[str]] = None
) -> str:
    stgcmd = [conf.stg, "new", f"--message={message}"]
    if argv:
        stgcmd += argv
    stgcmd += ["--", patchname]

    proc = subprocess.Popen(
        stgcmd,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    assert proc.stdout

    new_patchname = ""
    while True:
        line = proc.stdout.readline()
        if not line:
            if proc.poll() is not None:
                break
            continue
        print(line, end="")
        m = re.match(r'Now at patch "(.*)"', line)
        if m:
            new_patchname = m.group(1)

    return new_patchname


def command_new(args: argparse.Namespace, argv: list[str]):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    if args.message:
        message = args.message
    else:
        message = args.name

    # Run "stg new"
    patchname = run_stg_new(args.name, message, argv)
    if not patchname:
        sys.exit(1)

    commitid = ""  # get_stg_commitid(patchname)
    status_list += [StatusItem(commitid, patchname)]

    idx = get_last_applied_patch_idx(series_list) + 1
    series_list.insert(
        idx,
        SeriesItem(args.name, patchname, [], [], "applied", "unguarded", commitid),
    )

    write_series(series, series_list)
    write_status(status, status_list)


def run_stg_pop(popall: bool = False, number: int = 0) -> tuple[int, str]:
    stgcmd = [conf.stg, "pop"]
    if popall:
        stgcmd += ["--all"]
    elif number > 0:
        stgcmd += [f"--number={str(number)}"]

    proc = subprocess.Popen(
        stgcmd,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    assert proc.stdout

    patchname = ""
    while True:
        line = proc.stdout.readline()
        if not line:
            if proc.poll() is not None:
                break
            continue
        print(line, end="")
        m = re.match(r'Now at patch "(.*)"', line)
        if m:
            patchname = m.group(1)

    return proc.returncode, patchname


def get_pop_number(series_list: list[SeriesItem], patchname: str) -> int:
    n = -1
    for si in series_list:
        if si.applied == "applied":
            if si.patchfile == patchname or si.patchname == patchname:
                n = 0
            else:
                n += 1
    return n


def pop_patches(
    popall: Optional[bool] = None,
    number: Optional[int] = None,
    patchname: Optional[str] = None,
    ignore_nopatches: bool = False,
):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    if not get_last_applied_patch(series_list):
        if ignore_nopatches:
            return
        print("stq: No patches applied", file=sys.stderr)
        sys.exit(1)

    if patchname:
        number = get_pop_number(series_list, patchname)
        if number < 0:
            print(f"stq: Patch not found: {patchname}", file=sys.stderr)
            sys.exit(1)

    if number is None:
        number = 1
    if popall is None:
        popall = False

    ret, new_patchname = run_stg_pop(popall, number)
    if ret != 0:
        sys.exit(ret)

    last_idx = 0
    if new_patchname:
        for i, si in enumerate(status_list):
            if si.patchname == new_patchname:
                last_idx = i + 1
                break
    del status_list[last_idx:]
    write_status(status, status_list)


def command_pop(args: argparse.Namespace):
    pop_patches(args.all, args.number, args.patch)


def command_pull(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    # Run "stg pull"
    stgcmd = [conf.stg, "pull"]
    if args.nopush:
        stgcmd += ["--nopush"]
    if args.merged:
        stgcmd += ["--merged"]
    if args.repository:
        stgcmd += ["--", args.repository]
    res = subprocess.run(stgcmd)
    if res.returncode:
        sys.exit(res.returncode)

    # Update metadata
    patch_list = run_stg_series()
    update_series_by_stg_series(series_list, patch_list)

    write_series(series, series_list)
    write_status_from_series(status, series_list)


def run_stg_rename(newpatch: str, oldpatch: Optional[str] = None) -> tuple[bool, str]:
    stgcmd = [conf.stg, "rename", "--"]
    if oldpatch is not None:
        stgcmd += [oldpatch]
    stgcmd += [newpatch]

    proc = subprocess.Popen(
        stgcmd,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    assert proc.stdout

    while True:
        line = proc.stdout.readline()
        if not line:
            if proc.poll() is not None:
                break
            continue
        print(line, end="")
        m = re.match(r'Renaming patch "[^"]*" to "(.*)" \.\.\. done', line)
        if m:
            return True, m.group(1)

    return False, ""


def run_stg_import(patchfile: Path, patchname: Optional[str]) -> tuple[bool, str]:
    proc = subprocess.Popen(
        [conf.stg, "import", "--keep-cr", "--reject", "--", str(patchfile)],
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    assert proc.stdout

    if not patchname:
        patchname = patchfile.name

    apply_fail = False
    while True:
        line = proc.stdout.readline()
        if not line:
            if proc.poll() is not None:
                break
            continue
        print(line, end="")
        m = re.match(r'  Now at patch "(.*)"', line)
        if m:
            new_patchname = m.group(1)
            if patchname != new_patchname:
                # Try using patchname defined in series
                ok, new_patchname2 = run_stg_rename(patchname)
                if ok:
                    new_patchname = new_patchname2
            return True, new_patchname
        m = re.match(r"stg import: Patch does not apply cleanly", line)
        if m:
            apply_fail = True
            break

    if apply_fail:
        # Run "stg new" to prepare an empty patch
        message = patchfile.name  # Use patch file name as a temporary message
        patchname = run_stg_new(patchfile.name, message)
        if patchname:
            tmpf = tempfile.NamedTemporaryFile(
                mode="w+", encoding="utf-8", delete=False
            )
            # Extract the message from the patch file
            with patchfile.open("r") as f:
                for line in f:
                    if line.startswith("#"):
                        continue
                    if (
                        line.rstrip() == "---"
                        or line.startswith("--- ")
                        or line.startswith("diff --git")
                    ):
                        break
                    print(line, file=tmpf, end="")

            # Close the temp file.
            # This is mandatory on Windows. Otherwise, the file cannot be accessed
            # from another process.
            # From Python 3.12, delete=True with delete_on_close=False might be used.
            tmpf.close()

            # Apply the message
            _ = subprocess.run([conf.stg, "edit", f"--file={tmpf.name}"])

            os.unlink(tmpf.name)

        return False, patchname

    return False, ""


def run_stg_push(
    patchname_list: list[str],
) -> tuple[bool, list[tuple[str, bool]]]:
    res: list[tuple[str, bool]] = []
    if not patchname_list:
        return True, res

    stgcmd = [conf.stg, "push", "--"] + patchname_list
    proc = subprocess.Popen(
        stgcmd,
        encoding="utf-8",
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    assert proc.stdout

    while True:
        line = proc.stdout.readline()
        if not line:
            if proc.poll() is not None:
                break
            continue
        print(line, end="")
        m = re.match(r'Pushing patch "(.*)" ... done *(\(unmodified\))?', line)
        if m:
            unmodified = True if m.group(2) else False
            res += [(m.group(1), unmodified)]

    if proc.returncode != 0:
        return False, res
    return True, res


def push_patches(
    pushall: Optional[bool] = None,
    number: Optional[int] = None,
    move: Optional[bool] = None,
    patchname: Optional[str] = None,
):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    filtered_list = get_ungarded_patch_list(series_list)
    if not filtered_list:
        print("stq: Patch series already fully applied.", file=sys.stderr)
        sys.exit(1)

    if not pushall:
        idx = -1
        if patchname:
            idx = get_matching_patch_idx(filtered_list, patchname)
            if idx < 0:
                print(f"stq: Patch not found: {patchname}", file=sys.stderr)
                sys.exit(1)

        if move:
            if idx < 0:
                print("stq: Patch not specified", file=sys.stderr)
                sys.exit(1)
            si = filtered_list[idx]
            filtered_list = [si]
            # Reorder series_list
            series_list.remove(si)
            i = get_last_applied_patch_idx(series_list) + 1
            series_list.insert(i, si)
        else:
            if idx >= 0:
                number = idx + 1
            elif number is None:
                number = 1

            del filtered_list[number:]

    # Classify the patches:
    #  1. Not applied yet, already registered in stg series
    #  2. Not applied yet, not registered in stg series

    patch_list = run_stg_series("unapplied")

    patchname_list: list[str] = []
    sentinel = SeriesItem("", "", [], [])
    for si in filtered_list + [sentinel]:
        patchname = si.patchname if si.patchname else si.patchfile
        if si is not sentinel and (
            p := get_matching_patch_in_stg_series(patch_list, patchname)
        ):
            # Already, registered in stg
            patchname_list += [p.patchname]
            patch_list.remove(p)
        else:
            # Not registered in stg
            if patchname_list:
                # Push the registered patches first.
                ok, ret = run_stg_push(patchname_list)

                for patchname, unmodified in ret:
                    commitid = ""  # get_stg_commitid(patchname)
                    status_list += [StatusItem(commitid, patchname)]
                if not ok:
                    write_series(series, series_list)
                    write_status(status, status_list)
                    sys.exit(1)

                patchname_list = []

            if si is sentinel:
                break

            # Import the patch to stg
            print(f"Pushing patch file: {si.patchfile}")
            apply_cleanly, si.patchname = run_stg_import(
                patdir / si.patchfile, si.patchname
            )
            si.commitid = ""  # get_stg_commitid(si.patchname)
            status_list += [StatusItem(si.commitid, si.patchname)]

            if not apply_cleanly:
                write_series(series, series_list)
                write_status(status, status_list)
                sys.exit(1)

    write_series(series, series_list)
    write_status(status, status_list)


def command_push(args: argparse.Namespace):
    push_patches(args.all, args.number, args.move, args.patch)


def command_qgit(args: argparse.Namespace, argv: list[str]):
    patdir = ensure_patchesdir()

    gitcmd = [conf.git, "-C", str(patdir)] + argv
    res = subprocess.run(gitcmd)
    if res.returncode:
        sys.exit(res.returncode)


def refresh_patch(patdir: Path, si: SeriesItem):
    patchname = si.patchname
    assert patchname
    patchfile = si.patchfile
    print(f"Updating patch file: {patchfile}")

    with tempfile.TemporaryDirectory(dir=".") as tmpdirname:
        tmpdir = Path(tmpdirname)
        # Export the patch to tmpdir
        res = subprocess.run(
            [
                conf.stg,
                "export",
                f"--dir={tmpdirname}",
                "--",
                patchname,
            ]
        )
        if res.returncode:
            sys.exit(res.returncode)

        shutil.copy(tmpdir / patchname, patdir / patchfile)


def command_refresh(args: argparse.Namespace, argv: list[str]):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    si = get_last_applied_patch(series_list)
    if not si:
        print("stq: No patches applied", file=sys.stderr)
        sys.exit(1)

    # Run "stg refresh"
    res = subprocess.run([conf.stg, "refresh"] + argv)
    if res.returncode:
        sys.exit(res.returncode)

    if False:
        # Update commitid (disabled for now)
        patchname = si.patchname
        commitid = get_stg_commitid(patchname)
        if commitid:
            status_list[-1].commitid = commitid

        write_status(status, status_list)

    # Update the current patch file
    refresh_patch(patdir, si)


def command_rename(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    if args.patch2:
        si = get_matching_patch(series_list, args.patch1)
        if not si:
            print(f"stq: Patch file not found: {args.patch1}", file=sys.stderr)
            sys.exit(1)
        target = args.patch2
    else:
        si = get_last_applied_patch(series_list)
        if not si:
            print("stq: No patches applied", file=sys.stderr)
            sys.exit(1)
        target = args.patch1

    # Rename patch file
    target_path = patdir / target
    if target_path.exists():
        print(f"stq: Patch already exists: {target}", file=sys.stderr)
        sys.exit(1)
    shutil.move(patdir / si.patchfile, target_path)

    # Rename stg patchname if registered
    old_patchname = ""
    if si.applied == "applied":
        old_patchname = si.patchname
    else:
        patch_list = run_stg_series()
        if p := get_matching_patch_in_stg_series(patch_list, si.patchname):
            old_patchname = p.patchname
    if old_patchname:
        ok, patchname = run_stg_rename(target, old_patchname)
        if ok:
            si.patchname = patchname

    if not si.patchname:
        si.patchname = si.patchfile
    si.patchfile = target

    write_series(series, series_list)
    write_status_from_series(status, series_list)


def command_repair(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    if not args.skip_stg:
        # Fix StGit metadata
        _ = subprocess.run([conf.stg, "repair"])

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    # Update metadata
    patch_list = run_stg_series()
    update_series_by_stg_series(series_list, patch_list)

    if len(patch_list) > 0 and not args.skip_patch:
        print("Refreshing all the registered patches.")
        with tempfile.TemporaryDirectory(dir=".") as tmpdirname:
            tmpdir = Path(tmpdirname)
            if not args.skip_patch:
                # Export the patches to tmpdir
                res = subprocess.run(
                    [
                        conf.stg,
                        "export",
                        f"--dir={tmpdirname}",
                        "--",
                        f"{patch_list[0].patchname}..{patch_list[-1].patchname}",
                    ]
                )
                if res.returncode:
                    sys.exit(res.returncode)

            for si in series_list:
                if si.registered:
                    print(f"Updating: {si.patchfile}")
                    shutil.copy(tmpdir / si.patchname, patdir / si.patchfile)

    print("Updating: series")
    write_series(series, series_list)

    print("Updating: status")
    write_status_from_series(status, series_list)


def show_all_guards(series_list: list[SeriesItem]):
    pos = set()
    neg = set()
    for si in series_list:
        pos |= set(si.positive_guards)
        neg |= set(si.negative_guards)

    for i in sorted(pos | neg):
        if i in neg:
            print(f"-{i}")
        if i in pos:
            print(f"+{i}")


def command_select(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    if args.series:
        show_all_guards(series_list)
        return

    new_guards_list: list[str] = []
    if not args.none:
        if args.guard:
            new_guards_list = args.guard
        else:
            # No guards specified. Show current guards.
            for i in guards_list:
                print(i)
            return

    # TODO: Compare guards_list and new_guards_list.

    last_patchname = ""
    if args.pop or args.reapply:
        if args.reapply:
            if si := get_last_applied_patch(series_list):
                last_patchname = si.patchname
        pop_patches(popall=True, ignore_nopatches=True)

    write_guards(guards, new_guards_list)

    if args.reapply and last_patchname:
        # Reapply the unguarded patches until patchname
        new_patchname = ""
        update_series_by_guards(series_list, new_guards_list)
        for si in series_list:
            if si.guarded == "unguarded":
                new_patchname = si.patchname
            if si.patchname == last_patchname or si.patchfile == last_patchname:
                break
        if new_patchname:
            push_patches(patchname=new_patchname)


def command_series(args: argparse.Namespace):
    patdir = ensure_patchesdir()

    series = patdir / "series"
    series_list = read_series(series)
    status = patdir / "status"
    status_list = read_status(status)
    guards = patdir / "guards"
    guards_list = read_guards(guards)

    update_series_by_guards(series_list, guards_list)
    update_series_by_status(series_list, status_list)

    for si in series_list:
        if si.applied == "applied":
            print("+", f"{COL_APPLIED}{si.patchfile}{COL_OFF}")
        else:
            print("-", f"{COL_UNAPPLIED}{si.patchfile}{COL_OFF}")


def command_version(args: argparse.Namespace):
    print(f"stq {VERSION}")
    res = subprocess.run([conf.stg, "version"])
    sys.exit(res.returncode)


def command_help(args: argparse.Namespace):
    if args.command:
        cmd = get_subcommand(args.parser, args.subparsers, args.command)
        args.parser.parse_args([cmd, "--help"])
    else:
        args.parser.print_help()


def search_subcommand() -> tuple[int, str]:
    i = 0
    while i < len(sys.argv) - 1:
        i += 1
        arg = sys.argv[i]
        if arg.startswith("-"):
            if arg.startswith("-C="):
                continue
            if arg == "-C":
                i += 1
                continue
            if arg in ["-h", "--h", "--he", "--hel", "--help"]:
                return i, "help"
        else:
            return i, arg

    return -1, ""


def get_subcommand(
    parser: argparse.ArgumentParser, subparsers: argparse._SubParsersAction, cmd: str
) -> str:
    allcmds = subparsers._name_parser_map.keys()

    # Check exact match
    if cmd in allcmds:
        return cmd

    # Check abbreviated commands
    cmds = [x for x in allcmds if x.startswith(cmd)]

    if len(cmds) == 1:
        return cmds[0]
    else:
        if len(cmds) == 0:
            print(f'stq: Unknown subcommand: "{cmd}"', file=sys.stderr)
        else:
            print(
                f'stq: Ambiguous subcommand: "{cmd}" (candidates: {sorted(cmds)})',
                file=sys.stderr,
            )
        parser.print_usage(sys.stderr)
        sys.exit(1)


def enable_esc_seq():
    """Enable ANSI escape sequences

    This is useful on Windows 10 or later. Do nothing on other OSes.
    """
    if os.name != "nt":
        return

    from ctypes import byref, c_uint, windll

    STD_OUTPUT_HANDLE = c_uint(-11)
    ENABLE_VIRTUAL_TERMINAL_PROCESSING = 0x4

    out = windll.kernel32.GetStdHandle(STD_OUTPUT_HANDLE)
    mode = c_uint()
    windll.kernel32.GetConsoleMode(out, byref(mode))
    mode.value |= ENABLE_VIRTUAL_TERMINAL_PROCESSING
    windll.kernel32.SetConsoleMode(out, mode)


def main() -> None:
    enable_esc_seq()

    if os.getenv("NO_COLOR", "") != "":
        # Disable colors
        global \
            COL_APPLIED, \
            COL_UNAPPLIED, \
            COL_UNGUARDED, \
            COL_POS_GUARD, \
            COL_NEG_GUARD, \
            COL_OFF
        COL_APPLIED = ""
        COL_UNAPPLIED = ""
        COL_UNGUARDED = ""
        COL_POS_GUARD = ""
        COL_NEG_GUARD = ""
        COL_OFF = ""

    parser = argparse.ArgumentParser(
        description="stq: A Mercurial-Queues-like wrapper for StGit",
        exit_on_error=False,
    )
    subparsers = parser.add_subparsers()

    # clean
    parser_clean = subparsers.add_parser(
        "clean",
        help="delete the empty patches in the series",
        description="Delete the empty patches in the series.",
    )
    parser_clean.add_argument(
        "-a",
        "--applied",
        action="store_true",
        help="delete the empty applied patches",
    )
    parser_clean.add_argument(
        "-u",
        "--unapplied",
        action="store_true",
        help="delete the empty unapplied patches",
    )
    parser_clean.add_argument(
        "-k", "--keep", action="store_true", help="keep patch file"
    )
    parser_clean.set_defaults(handler=command_clean)

    # clone
    parser_clone = subparsers.add_parser(
        "clone",
        help="make a local clone of a remote repository",
        description="Make a local clone of a remote repository.",
    )
    parser_clone.add_argument("repository", help="remote repository to clone")
    parser_clone.add_argument("dir", help="local directory")
    parser_clone.add_argument(
        "-p",
        "--patches",
        help="patch repository to clone",
    )
    parser_clone.set_defaults(handler=command_clone)

    # delete
    parser_delete = subparsers.add_parser(
        "delete",
        aliases=["rm"],
        help="delete patches",
        description="Delete patches.",
    )
    parser_delete.add_argument(
        "-k", "--keep", action="store_true", help="keep patch file"
    )
    parser_delete.add_argument(
        "-t", "--top", action="store_true", help="delete top patch"
    )
    parser_delete.add_argument("patch", help="patch name(s)", nargs="*")
    parser_delete.set_defaults(handler=command_delete)

    # discard
    parser_discard = subparsers.add_parser(
        "discard",
        help="discard patches in StGit",
        description="Discard the StGit patches in the current branch to make it possible to reapply the patch files in the patches directory.",
    )
    discard_group = parser_discard.add_mutually_exclusive_group(required=True)
    discard_group.add_argument(
        "-a",
        "--all",
        action="store_true",
        help="discard all the StGit patches",
    )
    discard_group.add_argument(
        "-t",
        "--top",
        action="store_true",
        help="discard the top StGit patches",
    )
    parser_discard.set_defaults(handler=command_discard)

    # edit
    parser_edit = subparsers.add_parser(
        "edit",
        help="edit a patch description or diff",
        description='Edit a patch description or diff by invoking "stg edit [<args>]".',
    )
    parser_edit.set_defaults(handler=command_edit)

    # fold
    parser_fold = subparsers.add_parser(
        "fold",
        help="fold the named patches into the current patch",
        description="Fold the named patches into the current patch.",
    )
    parser_fold.add_argument(
        "-k", "--keep", action="store_true", help="keep folded patch files"
    )
    parser_fold.add_argument("patch", help="patch(es) to be folded", nargs="+")
    parser_fold.set_defaults(handler=command_fold)

    # guard
    parser_guard = subparsers.add_parser(
        "guard",
        help="set or print guards for a patch",
        description="Set or print guards for a patch.",
    )
    parser_guard.add_argument(
        "-l", "--list", action="store_true", help="list all patches and guards"
    )
    parser_guard.add_argument(
        "-n", "--none", action="store_true", help="drop all guards"
    )
    parser_guard.add_argument("patch", help="patch to apply guards", nargs="?")
    parser_guard.add_argument(
        "guard", help="name of guard(s). [+GUARD]... [-GUARD]...", nargs="*"
    )
    parser_guard.set_defaults(handler=command_guard)

    # import
    parser_import = subparsers.add_parser(
        "import", help="import a patch file", description="Import a patch file."
    )
    parser_import.add_argument(
        "patch",
        nargs="+",
        type=Path,
        help="patch file(s) to import",
    )
    parser_import.set_defaults(handler=command_import)

    # init
    parser_init = subparsers.add_parser(
        "init",
        help="initialize the stq directory",
        description="Initialize the stq directory.",
    )
    parser_init.add_argument(
        "-s", "--skip-stg", action="store_true", help="skip initializing StGit metadata"
    )
    parser_init.set_defaults(handler=command_init)

    # mqimport
    parser_mqimport = subparsers.add_parser(
        "mqimport",
        help="import Mercurial Queues patches",
        description="Import Mercurial Queue patches.",
    )
    parser_mqimport.add_argument(
        "mq_dir",
        type=Path,
        help="import all the MQ patches from MQ_DIR directory (E.g.: './hgrepo/.hg/patches/')",
    )
    parser_mqimport.set_defaults(handler=command_mqimport)

    # new
    parser_new = subparsers.add_parser(
        "new",
        help="create a new, empty patch",
        description="Create a new, empty patch.",
    )
    parser_new.add_argument("name", help="name of the new patch")
    parser_new.add_argument(
        "-m", "--message", help="use text as commit message (default: patch name)"
    )
    parser_new.set_defaults(handler=command_new)

    # pop
    parser_pop = subparsers.add_parser(
        "pop",
        help="pop the current patch off the stack",
        description="Pop the current patch off the stack.",
    )
    parser_pop.add_argument("-a", "--all", action="store_true", help="pop all patches")
    parser_pop.add_argument(
        "-n", "--number", type=int, help="pop the specified number of patches"
    )
    parser_pop.add_argument(
        "patch", help="pop patches until the specified patch", nargs="?"
    )
    parser_pop.set_defaults(handler=command_pop)

    # pull
    parser_pull = subparsers.add_parser(
        "pull",
        help="pull changes from a remote repository",
        description="Pull changes from a remote repository.",
    )
    parser_pull.add_argument(
        "-n",
        "--nopush",
        action="store_true",
        help="do not push the patches back after pulling",
    )
    parser_pull.add_argument(
        "-m",
        "--merged",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="check for patches merged upstream",
    )
    parser_pull.add_argument("repository", help="repository to pull from", nargs="?")
    parser_pull.set_defaults(handler=command_pull)

    # push
    parser_push = subparsers.add_parser(
        "push",
        help="push the next patch onto the stack",
        description="Push the next patch onto the stack.",
    )
    parser_push.add_argument(
        "-a", "--all", action="store_true", help="apply all patches"
    )
    parser_push.add_argument(
        "-n", "--number", type=int, help="push the specified number of patches"
    )
    parser_push.add_argument(
        "--move",
        action="store_true",
        help="reorder patch series and apply only the patch",
    )
    parser_push.add_argument(
        "patch", help="push patches until the specified patch", nargs="?"
    )
    parser_push.set_defaults(handler=command_push)

    # qgit
    parser_qgit = subparsers.add_parser(
        "qgit",
        help="run the git command in the patch queue directory",
        description="Run the git command in the patch queue directory.",
    )
    parser_qgit.set_defaults(handler=command_qgit)

    # refresh
    parser_refresh = subparsers.add_parser(
        "refresh",
        help="update the current patch",
        description="Update the current patch.",
    )
    parser_refresh.add_argument(
        "-e", "--edit", action="store_true", help="invoke editor on commit messages"
    )
    parser_refresh.set_defaults(handler=command_refresh)

    # rename
    parser_rename = subparsers.add_parser(
        "rename",
        aliases=["mv"],
        help="rename a patch",
        description="Rename a patch. With one argument, renames the current patch to PATCH1. With two arguments, renames PATCH1 to PATCH2.",
    )
    parser_rename.add_argument("patch1", help="1st patch file name")
    parser_rename.add_argument("patch2", help="2nd patch file name", nargs="?")
    parser_rename.set_defaults(handler=command_rename)

    # repair
    parser_repair = subparsers.add_parser(
        "repair",
        help="fix stq metadata",
        description="Fix stq metadata and update the patch files based on the current StGit status. Also fix StGit metadata.",
    )
    parser_repair.add_argument(
        "-s", "--skip-stg", action="store_true", help="skip fixing StGit metadata"
    )
    parser_repair.add_argument(
        "-p", "--skip-patch", action="store_true", help="skip updating patch files"
    )
    parser_repair.set_defaults(handler=command_repair)

    # select
    parser_select = subparsers.add_parser(
        "select",
        help="set or print guarded patches to push",
        description="Set or print guarded patches to push.",
    )
    parser_select.add_argument(
        "-n", "--none", action="store_true", help="disable all guards"
    )
    parser_select.add_argument(
        "-s", "--series", action="store_true", help="list all guards in series file"
    )
    parser_select.add_argument(
        "--pop", action="store_true", help="pop to before first guarded applied patch"
    )
    parser_select.add_argument(
        "--reapply", action="store_true", help="pop, then reapply patches"
    )
    parser_select.add_argument(
        "guard",
        nargs="*",
        help="guard(s) to be selected",
    )
    parser_select.set_defaults(handler=command_select)

    # series
    parser_series = subparsers.add_parser(
        "series",
        help="print the entire series file",
        description="Print the entire series file.",
    )
    parser_series.set_defaults(handler=command_series)

    # version
    parser_version = subparsers.add_parser(
        "version",
        help="show the version",
        description="Show the version",
    )
    parser_version.set_defaults(handler=command_version)

    # help
    parser_help = subparsers.add_parser(
        "help", help="show the help of the specified subcommand"
    )
    parser_help.add_argument(
        "command", nargs="?", help="command name which help is shown"
    )
    parser_help.set_defaults(handler=command_help, parser=parser, subparsers=subparsers)

    # Common options
    parser.add_argument("-C", dest="path", type=Path, help="set current directory")
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="enable additional output"
    )

    idx, cmd = search_subcommand()
    if idx < 0:
        parser.print_help()
        sys.exit(0)
    cmd = get_subcommand(parser, subparsers, cmd)
    sub_argv = sys.argv[idx + 1 :]
    args, argv = parser.parse_known_args(sys.argv[1:idx] + [cmd] + sub_argv)

    if args.path:
        os.chdir(args.path)

    if hasattr(args, "handler"):
        if args.handler in [command_edit, command_new, command_qgit, command_refresh]:
            # Pass unrecognized args to the handler.
            return args.handler(args, argv)

        if argv:
            msg = "unrecognized arguments: %s"
            parser.error(msg % " ".join(argv))
        return args.handler(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
